"""Init models with SearchTask

Revision ID: 3106acda96a6
Revises: 
Create Date: 2026-03-28 18:15:40.286632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3106acda96a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_market_id'), 'products', ['market_id'], unique=True)
    op.create_index(op.f('ix_products_platform'), 'products', ['platform'], unique=False)
    op.create_table('search_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('min_price', sa.Integer(), nullable=True),
    sa.Column('max_price', sa.Integer(), nullable=True),
    sa.Column('platforms', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_tasks_keyword'), 'search_tasks', ['keyword'], unique=False)
    op.create_index(op.f('ix_search_tasks_user_id'), 'search_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_tasks_user_id'), table_name='search_tasks')
    op.drop_index(op.f('ix_search_tasks_keyword'), table_name='search_tasks')
    op.drop_table('search_tasks')
    op.drop_index(op.f('ix_products_platform'), table_name='products')
    op.drop_index(op.f('ix_products_market_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
